spring.application.name=careernexus

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/careernexus
spring.datasource.username=postgres
spring.datasource.password=12345

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.open-in-view=false

careernexus.jwt.secret=536f6d6552616e646f6d4c6f6e675365637265744b6579466f724361726565724e65787573506c6174666f726d4261636b656e6432303236
careernexus.jwt.expiration=86400000